language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 8
  - node
before_script:
  - cp default.config.json config.json
after_script:
  - npm run coverage
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1

